Repository buildtesters/schemas, pull requests merged in 2020-03, with the labels that each got.

#14 adding pre_run, post_run, and shell as required sections
  .github/tests/test_organization.py
  README.md
  script/README.md
  script/script-v0.0.1.schema.json
Labels: size/M, ✅ Approved

#15 adding missing env array
  .github/tests/__pycache__/test_organization.cpython-37-pytest-5.2.1.pyc
  .github/tests/test_organization.py
  .gitignore
  README.md
  script/README.md
  script/examples/0.0.1/slurm.yml
  script/script-v0.0.1.schema.json
Labels: size/S, ✅ Approved

#16 add pre_build, post_build, and build as suggested sections
  README.md
  script/README.md
Labels: size/M, ✅ Approved

#18 limiting user to bash or python or shell
  script/script-v0.0.1.schema.json
Labels: size/XS, ✅ Approved

#19 Revert "limiting user to bash or python or shell"
  script/script-v0.0.1.schema.json
Labels: size/XS, 🔍 Ready for Review

#20 add executor key to script schema
  script/README.md
  script/script-v0.0.1.schema.json
Labels: size/XS, ✅ Approved
